// <auto-generated />
namespace zazi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class change_require_name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_require_name));
        
        string IMigrationMetadata.Id
        {
            get { return "201410280736491_change_require_name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
